### ISSUE TITLE
can't transfer picture from one collection to another

### ISSUE THREAD

**Issue by eephyne** [spillz/picty#7]
Hi

I just started using picty because it suit exactly my need but I don't succed at transferring picture.

I created a new collection, opened a external sd card and tried to transfer from the sd card to the new collection and I got that

2015-07-29 09:47:03,751 - picty core - ERROR
Error on Worker Thread
Traceback (most recent call last):
  File "/home/midee/build/picty/modules/picty/backend.py", line 1250, in _loop
    if job():
  File "/home/midee/build/picty/modules/picty/plugins/transfer.py", line 111, in __call__
    gobject.idle_add(self.browser.update_status,1.0*i/self.count,'Transferring media - %i of %i'%(i,self.count))
AttributeError: TransferImportJob instance has no attribute 'count'

ERROR:picty core:Error on Worker Thread
Traceback (most recent call last):
  File "/home/midee/build/picty/modules/picty/backend.py", line 1250, in _loop
    if job():
  File "/home/midee/build/picty/modules/picty/plugins/transfer.py", line 111, in __call__
    gobject.idle_add(self.browser.update_status,1.0*i/self.count,'Transferring media - %i of %i'%(i,self.count))
AttributeError: TransferImportJob instance has no attribute 'count'

INFO:picty core:Abandoning Highest Priority Task TRANSFER and Resuming Worker Loop

I searched for this error but I don' found anything useful for now

I assume this is probably related to one of my lib but I'm not sure

**Comment by spillz** [comment]
Silly bug. Fixed and thanks for reporting.
