### ISSUE TITLE
error when creating thumbnail

### ISSUE THREAD

**Issue by eephyne** [spillz/picty#8]
here another one :)

for each thumbnail to generate (I'm not on the same machine than before, here I'm on arch and back then it was an ubuntu ).

2015-07-29 11:20:12,837 - picty core - ERROR
Error on Worker Thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/picty/backend.py", line 1250, in _loop
    if job():
  File "/usr/lib/python2.7/site-packages/picty/backend.py", line 230, in __call
__
    if item.thumb!=False and not self.collection.has_thumbnail(item):
  File "/usr/lib/python2.7/site-packages/picty/collectiontypes/localstorebin.py
", line 875, in has_thumbnail
    return imagemanip.has_thumb(item,self,self.thumbnail_cache_dir)
  File "/usr/lib/python2.7/site-packages/picty/imagemanip.py", line 814, in has
_thumb
    item.thumburi=thumb_factory.lookup(uri,int(item.mtime))
AttributeError: 'NoneType' object has no attribute 'lookup

**Comment by eephyne** [comment]
Nevermind I found that was gnome.ui that wasn't there (gnome-python package in arch not python2-gnome2)

**Comment by spillz** [comment]
Still, should be able to handle that one more gracefully.

**Comment by eephyne** [comment]
I played with the try catch when you set thumbnail_factory to discover that was gnome.ui missing so maybe removing it or only try for windows since it seem to be the main reason of this try catch
